const KEY='deanti_bakery_v1';
const today=()=>new Date().toISOString().slice(0,10);
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const seed={products:[
  {id:id(),name:'Roti Coklat',category:'Roti',price:8000,cost:4000,stock:35},
  {id:id(),name:'Roti Keju',category:'Roti',price:9000,cost:4500,stock:28},
  {id:id(),name:'Donat Gula',category:'Donat',price:6000,cost:2800,stock:40},
  {id:id(),name:'Brownies',category:'Kue',price:45000,cost:24000,stock:12},
  {id:id(),name:'Bolu Pisang',category:'Kue',price:35000,cost:19000,stock:10},
  {id:id(),name:'Croissant',category:'Pastry',price:15000,cost:8000,stock:18}
],transactions:[],cashflows:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; let cart=[]; let chart;
function save(){localStorage.setItem(KEY,JSON.stringify(db)); renderAll()}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function esc(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('page-'+page).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const names={dashboard:['Dashboard','Ringkasan usaha hari ini'],kasir:['Kasir','Penjualan dan pembayaran'],produk:['Produk & Stok','Kelola produk dan persediaan'],transaksi:['Transaksi','Riwayat penjualan'],keuangan:['Keuangan','Pemasukan dan pengeluaran'],laporan:['Laporan','Rekap usaha']};document.getElementById('pageTitle').textContent=names[page][0];document.getElementById('pageSub').textContent=names[page][1];renderAll()}
function txTotal(t){return t.items.reduce((a,i)=>a+i.price*i.qty,0)-t.discount}
function todayTx(){return db.transactions.filter(t=>t.date===today())}
function renderDashboard(){const tx=todayTx(),sales=tx.reduce((a,t)=>a+txTotal(t),0),profit=tx.reduce((a,t)=>a+t.items.reduce((x,i)=>x+(i.price-i.cost)*i.qty,0)-t.discount,0),expense=db.cashflows.filter(x=>x.date===today()&&x.type==='expense').reduce((a,x)=>a+x.amount,0),stock=db.products.reduce((a,p)=>a+p.price*p.stock,0);document.getElementById('statSales').textContent=rupiah(sales);document.getElementById('statSalesCount').textContent=`${tx.length} transaksi`;document.getElementById('statProfit').textContent=rupiah(profit);document.getElementById('statExpense').textContent=rupiah(expense);document.getElementById('statStock').textContent=rupiah(stock);document.getElementById('statStockCount').textContent=`${db.products.length} produk`;const counts={};tx.flatMap(t=>t.items).forEach(i=>counts[i.name]=(counts[i.name]||0)+i.qty);const best=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5);document.getElementById('bestSellerList').innerHTML=best.length?best.map((x,i)=>`<div class="list-item"><span>${i+1}. ${esc(x[0])}</span><strong>${x[1]} terjual</strong></div>`).join(''):'<p style="color:var(--muted)">Belum ada transaksi.</p>';document.getElementById('recentTransactions').innerHTML=tableTx(tx.slice().reverse().slice(0,7));drawChart()}
function drawChart(){const vals=[],labels=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const ds=d.toISOString().slice(0,10);labels.push(d.toLocaleDateString('id-ID',{day:'2-digit',month:'short'}));vals.push(db.transactions.filter(t=>t.date===ds).reduce((a,t)=>a+txTotal(t),0))}const c=document.getElementById('salesChart');if(!c)return;if(chart)chart.destroy();chart=new Chart(c,{type:'line',data:{labels,datasets:[{label:'Omzet',data:vals,tension:.35,fill:true}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>rupiah(v)}}}}})}
function tableTx(rows){if(!rows.length)return '<p style="color:var(--muted)">Belum ada data transaksi.</p>';return `<table><thead><tr><th>No. Transaksi</th><th>Waktu</th><th>Total</th><th>Metode</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(t.no)}</td><td>${esc(t.date)} ${esc(t.time)}</td><td class="money">${rupiah(txTotal(t))}</td><td><span class="badge">${esc(t.method)}</span></td></tr>`).join('')}</tbody></table>`}
function renderPOS(){const q=(document.getElementById('productSearch')?.value||'').toLowerCase();const ps=db.products.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q));document.getElementById('posProducts').innerHTML=ps.map(p=>`<div class="product-card" onclick="addCart('${p.id}')"><span class="cat">${esc(p.category)}</span><strong>${esc(p.name)}</strong><div class="price">${rupiah(p.price)}</div><div class="stock">Stok ${p.stock}</div></div>`).join('')||'<p style="color:var(--muted)">Produk tidak ditemukan.</p>';const c=document.getElementById('cartItems');if(!cart.length)c.innerHTML='<p style="color:var(--muted);padding:15px 0">Keranjang masih kosong.</p>';else c.innerHTML=cart.map(i=>`<div class="cart-row"><div><h4>${esc(i.name)}</h4><small>${rupiah(i.price)} × ${i.qty}</small></div><div class="qty-controls"><button onclick="changeQty('${i.id}',-1)">−</button><b>${i.qty}</b><button onclick="changeQty('${i.id}',1)">＋</button></div></div>`).join('');const sub=cart.reduce((a,i)=>a+i.price*i.qty,0),disc=Number(document.getElementById('discount')?.value||0);document.getElementById('cartSubtotal').textContent=rupiah(sub);document.getElementById('cartTotal').textContent=rupiah(Math.max(0,sub-disc));const paid=Number(document.getElementById('paidAmount')?.value||0);document.getElementById('changeAmount').textContent=rupiah(Math.max(0,paid-Math.max(0,sub-disc)))}
function addCart(pid){const p=db.products.find(x=>x.id===pid);if(!p||p.stock<=0)return toast('Stok produk habis');const i=cart.find(x=>x.id===pid);if(i){if(i.qty>=p.stock)return toast('Stok tidak cukup');i.qty++}else cart.push({...p,qty:1});renderPOS()}
function changeQty(pid,delta){const i=cart.find(x=>x.id===pid);if(!i)return;i.qty+=delta;if(i.qty<=0)cart=cart.filter(x=>x.id!==pid);else if(i.qty>db.products.find(p=>p.id===pid).stock)i.qty=db.products.find(p=>p.id===pid).stock;renderPOS()}
function checkout(){if(!cart.length)return toast('Keranjang kosong');const sub=cart.reduce((a,i)=>a+i.price*i.qty,0),discount=Number(document.getElementById('discount').value||0),total=Math.max(0,sub-discount),paid=Number(document.getElementById('paidAmount').value||0);if(paid<total)return toast('Nominal bayar kurang');cart.forEach(i=>{db.products.find(p=>p.id===i.id).stock-=i.qty});const now=new Date();const t={id:id(),no:'INV-'+now.toISOString().replace(/[-:TZ.]/g,'').slice(0,14),date:today(),time:now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),method:document.getElementById('paymentMethod').value,discount,items:cart.map(i=>({id:i.id,name:i.name,price:i.price,cost:i.cost,qty:i.qty}))};db.transactions.push(t);db.cashflows.push({id:id(),date:today(),time:t.time,type:'income',category:'Penjualan',description:t.no,amount:total});cart=[];document.getElementById('paidAmount').value='';document.getElementById('discount').value=0;save();toast('Transaksi berhasil disimpan')}
function renderProducts(){document.getElementById('productsTable').innerHTML=`<table><thead><tr><th>Produk</th><th>Kategori</th><th>Harga</th><th>HPP</th><th>Stok</th><th>Aksi</th></tr></thead><tbody>${db.products.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category)}</td><td>${rupiah(p.price)}</td><td>${rupiah(p.cost)}</td><td><span class="badge ${p.stock<=5?'red':'green'}">${p.stock}</span></td><td><button class="text-btn" onclick="editProduct('${p.id}')">Edit</button> <button class="text-btn danger" onclick="deleteProduct('${p.id}')">Hapus</button></td></tr>`).join('')}</tbody></table>`}
function openProduct(p=null){document.getElementById('modal').classList.remove('hidden');document.getElementById('modalTitle').textContent=p?'Edit Produk':'Tambah Produk';document.getElementById('productId').value=p?.id||'';document.getElementById('productName').value=p?.name||'';document.getElementById('productCategory').value=p?.category||'';document.getElementById('productPrice').value=p?.price||'';document.getElementById('productCost').value=p?.cost||'';document.getElementById('productStock').value=p?.stock||''}
function editProduct(pid){openProduct(db.products.find(p=>p.id===pid))}function deleteProduct(pid){if(confirm('Hapus produk ini?')){db.products=db.products.filter(p=>p.id!==pid);save();toast('Produk dihapus')}}
function renderTransactions(){const q=(document.getElementById('transactionSearch')?.value||'').toLowerCase(),m=document.getElementById('transactionMethod')?.value||'';let rows=db.transactions.slice().reverse();if(q)rows=rows.filter(t=>t.no.toLowerCase().includes(q));if(m)rows=rows.filter(t=>t.method===m);document.getElementById('transactionsTable').innerHTML=tableTx(rows)}
function renderCashflow(){const rows=db.cashflows.slice().reverse().slice(0,100);document.getElementById('cashflowTable').innerHTML=rows.length?`<table><thead><tr><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td><span class="badge ${x.type==='income'?'green':'red'}">${x.type==='income'?'Masuk':'Keluar'}</span></td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td class="money">${rupiah(x.amount)}</td></tr>`).join('')}</tbody></table>`:'<p style="color:var(--muted)">Belum ada arus kas.</p>'}
function renderReports(){const s=db.transactions.reduce((a,t)=>a+txTotal(t),0),e=db.cashflows.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),p=db.transactions.reduce((a,t)=>a+t.items.reduce((x,i)=>x+(i.price-i.cost)*i.qty,0)-t.discount,0);document.getElementById('reportSales').textContent=rupiah(s);document.getElementById('reportExpense').textContent=rupiah(e);document.getElementById('reportProfit').textContent=rupiah(p);document.getElementById('reportCount').textContent=db.transactions.length;const map={};db.transactions.flatMap(t=>t.items).forEach(i=>{if(!map[i.id])map[i.id]={name:i.name,qty:0,sales:0,hpp:0};map[i.id].qty+=i.qty;map[i.id].sales+=i.price*i.qty;map[i.id].hpp+=i.cost*i.qty});document.getElementById('reportProducts').innerHTML=Object.values(map).sort((a,b)=>b.sales-a.sales).length?`<table><thead><tr><th>Produk</th><th>Terjual</th><th>Penjualan</th><th>HPP</th><th>Margin</th></tr></thead><tbody>${Object.values(map).sort((a,b)=>b.sales-a.sales).map(x=>`<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${rupiah(x.sales)}</td><td>${rupiah(x.hpp)}</td><td class="money">${rupiah(x.sales-x.hpp)}</td></tr>`).join('')}</tbody></table>`:'<p style="color:var(--muted)">Belum ada penjualan.</p>'}
function renderAll(){renderDashboard();renderPOS();renderProducts();renderTransactions();renderCashflow();renderReports()}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.goto)));
document.getElementById('productSearch').addEventListener('input',renderPOS);document.getElementById('discount').addEventListener('input',renderPOS);document.getElementById('paidAmount').addEventListener('input',renderPOS);document.getElementById('checkoutBtn').addEventListener('click',checkout);document.getElementById('clearCart').addEventListener('click',()=>{cart=[];renderPOS()});document.getElementById('transactionSearch').addEventListener('input',renderTransactions);document.getElementById('transactionMethod').addEventListener('change',renderTransactions);document.getElementById('addProductBtn').addEventListener('click',()=>openProduct());document.getElementById('closeModal').addEventListener('click',()=>document.getElementById('modal').classList.add('hidden'));document.getElementById('productForm').addEventListener('submit',e=>{e.preventDefault();const pid=document.getElementById('productId').value,p={id:pid||id(),name:document.getElementById('productName').value.trim(),category:document.getElementById('productCategory').value.trim(),price:Number(document.getElementById('productPrice').value),cost:Number(document.getElementById('productCost').value),stock:Number(document.getElementById('productStock').value)};if(pid){const idx=db.products.findIndex(x=>x.id===pid);db.products[idx]=p}else db.products.push(p);document.getElementById('modal').classList.add('hidden');save();toast('Produk berhasil disimpan')});document.getElementById('incomeForm').addEventListener('submit',e=>{e.preventDefault();db.cashflows.push({id:id(),date:today(),time:new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),type:'income',category:'Lainnya',description:document.getElementById('incomeDesc').value,amount:Number(document.getElementById('incomeAmount').value)});e.target.reset();save();toast('Pemasukan disimpan')});document.getElementById('expenseForm').addEventListener('submit',e=>{e.preventDefault();db.cashflows.push({id:id(),date:today(),time:new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),type:'expense',category:'Operasional',description:document.getElementById('expenseDesc').value,amount:Number(document.getElementById('expenseAmount').value)});e.target.reset();save();toast('Pengeluaran disimpan')});document.getElementById('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`deanti-bakery-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)});document.getElementById('reportDate').value=today();renderAll();
