const LOCAL_KEY='deanti_bakery_v2';
const API_KEY='deanti_bakery_api_url';
const today=()=>new Date().toISOString().slice(0,10);
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const seed={products:[{id:uid(),name:'Roti Coklat',category:'Roti',price:8000,cost:4000,stock:35},{id:uid(),name:'Roti Keju',category:'Roti',price:9000,cost:4500,stock:28},{id:uid(),name:'Donat Gula',category:'Donat',price:6000,cost:2800,stock:40},{id:uid(),name:'Brownies',category:'Kue',price:45000,cost:24000,stock:12},{id:uid(),name:'Bolu Pisang',category:'Kue',price:35000,cost:19000,stock:10},{id:uid(),name:'Croissant',category:'Pastry',price:15000,cost:8000,stock:18}],transactions:[],cashflows:[]};
let db=JSON.parse(localStorage.getItem(LOCAL_KEY)||'null')||seed,cart=[],chart;
const apiUrl=()=>localStorage.getItem(API_KEY)||'';
function setStatus(online){document.getElementById('statusDot').style.background=online?'#49b47b':'#d18a3d';document.getElementById('storageStatus').textContent=online?'Google Sheets Terhubung':'Mode Lokal'}
function localSave(){localStorage.setItem(LOCAL_KEY,JSON.stringify(db));renderAll()}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function esc(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function txTotal(t){return t.items.reduce((a,i)=>a+Number(i.price)*Number(i.qty),0)-Number(t.discount||0)}
function todayTx(){return db.transactions.filter(t=>t.date===today())}
async function apiGet(action){const u=apiUrl();if(!u)throw Error('URL API belum diisi');const r=await fetch(u+'?action='+encodeURIComponent(action),{cache:'no-store'});const j=await r.json();if(!j.ok)throw Error(j.error||'API error');return j.data}
async function apiPost(action,data={}){const u=apiUrl();if(!u)throw Error('URL API belum diisi');const r=await fetch(u,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...data})});const j=await r.json();if(!j.ok)throw Error(j.error||'API error');return j.data}
async function syncFromSheets(){if(!apiUrl()){setStatus(false);return}try{db=await apiGet('bootstrap');localStorage.setItem(LOCAL_KEY,JSON.stringify(db));setStatus(true);renderAll();toast('Data berhasil disinkronkan')}catch(e){setStatus(false);toast('Gagal sinkron: '+e.message)}}
function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('page-'+page).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const n={dashboard:['Dashboard','Ringkasan usaha hari ini'],kasir:['Kasir','Penjualan dan pembayaran'],produk:['Produk & Stok','Kelola produk dan persediaan'],transaksi:['Transaksi','Riwayat penjualan'],keuangan:['Keuangan','Pemasukan dan pengeluaran'],laporan:['Laporan','Rekap usaha'],pengaturan:['Pengaturan','Koneksi database Google Sheets']};document.getElementById('pageTitle').textContent=n[page][0];document.getElementById('pageSub').textContent=n[page][1];renderAll()}
function renderDashboard(){const tx=todayTx(),sales=tx.reduce((a,t)=>a+txTotal(t),0),profit=tx.reduce((a,t)=>a+t.items.reduce((x,i)=>x+(Number(i.price)-Number(i.cost))*Number(i.qty),0)-Number(t.discount||0),0),expense=db.cashflows.filter(x=>x.date===today()&&x.type==='expense').reduce((a,x)=>a+Number(x.amount),0),stock=db.products.reduce((a,p)=>a+Number(p.price)*Number(p.stock),0);document.getElementById('statSales').textContent=rupiah(sales);document.getElementById('statSalesCount').textContent=`${tx.length} transaksi`;document.getElementById('statProfit').textContent=rupiah(profit);document.getElementById('statExpense').textContent=rupiah(expense);document.getElementById('statStock').textContent=rupiah(stock);document.getElementById('statStockCount').textContent=`${db.products.length} produk`;const c={};tx.flatMap(t=>t.items).forEach(i=>c[i.name]=(c[i.name]||0)+Number(i.qty));const best=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,5);document.getElementById('bestSellerList').innerHTML=best.length?best.map((x,i)=>`<div class="list-item"><span>${i+1}. ${esc(x[0])}</span><strong>${x[1]} terjual</strong></div>`).join(''):'<p style="color:var(--muted)">Belum ada transaksi.</p>';document.getElementById('recentTransactions').innerHTML=tableTx(tx.slice().reverse().slice(0,7));drawChart()}
function drawChart(){const vals=[],labels=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);labels.push(d.toLocaleDateString('id-ID',{day:'2-digit',month:'short'}));const ds=d.toISOString().slice(0,10);vals.push(db.transactions.filter(t=>t.date===ds).reduce((a,t)=>a+txTotal(t),0))}const c=document.getElementById('salesChart');if(!c)return;if(chart)chart.destroy();chart=new Chart(c,{type:'line',data:{labels,datasets:[{label:'Omzet',data:vals,tension:.35,fill:true}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>rupiah(v)}}}}})}
function tableTx(rows){if(!rows.length)return '<p style="color:var(--muted)">Belum ada data transaksi.</p>';return `<table><thead><tr><th>No. Transaksi</th><th>Waktu</th><th>Total</th><th>Metode</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(t.no)}</td><td>${esc(t.date)} ${esc(t.time)}</td><td class="money">${rupiah(txTotal(t))}</td><td><span class="badge">${esc(t.method)}</span></td></tr>`).join('')}</tbody></table>`}
function renderPOS(){const q=(document.getElementById('productSearch')?.value||'').toLowerCase();const ps=db.products.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q));document.getElementById('posProducts').innerHTML=ps.map(p=>`<div class="product-card ${Number(p.stock)<=0?'disabled':''}" onclick="addCart('${p.id}')"><span class="cat">${esc(p.category)}</span><strong>${esc(p.name)}</strong><div class="price">${rupiah(p.price)}</div><div class="stock">Stok ${p.stock}</div></div>`).join('')||'<p style="color:var(--muted)">Produk tidak ditemukan.</p>';document.getElementById('cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><div><h4>${esc(i.name)}</h4><small>${rupiah(i.price)} × ${i.qty}</small></div><div class="qty-controls"><button onclick="changeQty('${i.id}',-1)">−</button><b>${i.qty}</b><button onclick="changeQty('${i.id}',1)">＋</button></div></div>`).join(''):'<p style="color:var(--muted);padding:15px 0">Keranjang masih kosong.</p>';const sub=cart.reduce((a,i)=>a+i.price*i.qty,0),disc=Number(document.getElementById('discount')?.value||0),total=Math.max(0,sub-disc),paid=Number(document.getElementById('paidAmount')?.value||0);document.getElementById('cartSubtotal').textContent=rupiah(sub);document.getElementById('cartTotal').textContent=rupiah(total);document.getElementById('changeAmount').textContent=rupiah(Math.max(0,paid-total))}
function addCart(pid){const p=db.products.find(x=>x.id===pid);if(!p||Number(p.stock)<=0)return toast('Stok produk habis');const i=cart.find(x=>x.id===pid);if(i){if(i.qty>=Number(p.stock))return toast('Stok tidak cukup');i.qty++}else cart.push({...p,qty:1});renderPOS()}
function changeQty(pid,delta){const i=cart.find(x=>x.id===pid);if(!i)return;i.qty+=delta;if(i.qty<=0)cart=cart.filter(x=>x.id!==pid);else{i.qty=Math.min(i.qty,Number(db.products.find(p=>p.id===pid)?.stock||0))}renderPOS()}
async function checkout(){if(!cart.length)return toast('Keranjang kosong');const sub=cart.reduce((a,i)=>a+i.price*i.qty,0),discount=Number(document.getElementById('discount').value||0),total=Math.max(0,sub-discount),paid=Number(document.getElementById('paidAmount').value||0);if(paid<total)return toast('Nominal bayar kurang');const now=new Date(),t={id:uid(),no:'INV-'+now.toISOString().replace(/[-:TZ.]/g,'').slice(0,14),date:today(),time:now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),method:document.getElementById('paymentMethod').value,discount,items:cart.map(i=>({id:i.id,name:i.name,price:Number(i.price),cost:Number(i.cost),qty:Number(i.qty)}))};try{if(apiUrl()){db=await apiPost('checkout',{transaction:t});setStatus(true)}else{cart.forEach(i=>db.products.find(p=>p.id===i.id).stock-=i.qty);db.transactions.push(t);db.cashflows.push({id:uid(),date:t.date,time:t.time,type:'income',category:'Penjualan',description:t.no,amount:total});localSave()}cart=[];document.getElementById('paidAmount').value='';document.getElementById('discount').value=0;renderAll();toast('Transaksi berhasil disimpan')}catch(e){toast('Transaksi gagal: '+e.message)}}
function renderProducts(){document.getElementById('productsTable').innerHTML=`<table><thead><tr><th>Produk</th><th>Kategori</th><th>Harga</th><th>HPP</th><th>Stok</th><th>Aksi</th></tr></thead><tbody>${db.products.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category)}</td><td>${rupiah(p.price)}</td><td>${rupiah(p.cost)}</td><td><span class="badge ${Number(p.stock)<=5?'red':'green'}">${p.stock}</span></td><td><button class="text-btn" onclick="editProduct('${p.id}')">Edit</button> <button class="text-btn danger" onclick="deleteProduct('${p.id}')">Hapus</button></td></tr>`).join('')}</tbody></table>`}
function openProduct(p=null){document.getElementById('modal').classList.remove('hidden');document.getElementById('modalTitle').textContent=p?'Edit Produk':'Tambah Produk';document.getElementById('productId').value=p?.id||'';document.getElementById('productName').value=p?.name||'';document.getElementById('productCategory').value=p?.category||'';document.getElementById('productPrice').value=p?.price||'';document.getElementById('productCost').value=p?.cost||'';document.getElementById('productStock').value=p?.stock??''}
function editProduct(pid){openProduct(db.products.find(p=>p.id===pid))}
async function deleteProduct(pid){if(!confirm('Hapus produk ini?'))return;try{if(apiUrl()){db=await apiPost('deleteProduct',{id:pid});setStatus(true)}else{db.products=db.products.filter(p=>p.id!==pid);localSave()}renderAll();toast('Produk dihapus')}catch(e){toast('Gagal menghapus: '+e.message)}}
function renderTransactions(){const q=(document.getElementById('transactionSearch')?.value||'').toLowerCase(),m=document.getElementById('transactionMethod')?.value||'';let rows=db.transactions.slice().reverse();if(q)rows=rows.filter(t=>t.no.toLowerCase().includes(q));if(m)rows=rows.filter(t=>t.method===m);document.getElementById('transactionsTable').innerHTML=tableTx(rows)}
function renderCashflow(){const rows=db.cashflows.slice().reverse().slice(0,100);document.getElementById('cashflowTable').innerHTML=rows.length?`<table><thead><tr><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td><span class="badge ${x.type==='income'?'green':'red'}">${x.type==='income'?'Masuk':'Keluar'}</span></td><td>${esc(x.category)}</td><td>${esc(x.description)}</td><td class="money">${rupiah(x.amount)}</td></tr>`).join('')}</tbody></table>`:'<p style="color:var(--muted)">Belum ada arus kas.</p>'}
function renderReports(){const s=db.transactions.reduce((a,t)=>a+txTotal(t),0),e=db.cashflows.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0),p=db.transactions.reduce((a,t)=>a+t.items.reduce((x,i)=>x+(Number(i.price)-Number(i.cost))*Number(i.qty),0)-Number(t.discount||0),0);document.getElementById('reportSales').textContent=rupiah(s);document.getElementById('reportExpense').textContent=rupiah(e);document.getElementById('reportProfit').textContent=rupiah(p);document.getElementById('reportCount').textContent=db.transactions.length;const map={};db.transactions.flatMap(t=>t.items).forEach(i=>{if(!map[i.id])map[i.id]={name:i.name,qty:0,sales:0,hpp:0};map[i.id].qty+=Number(i.qty);map[i.id].sales+=Number(i.price)*Number(i.qty);map[i.id].hpp+=Number(i.cost)*Number(i.qty)});const rows=Object.values(map).sort((a,b)=>b.sales-a.sales);document.getElementById('reportProducts').innerHTML=rows.length?`<table><thead><tr><th>Produk</th><th>Terjual</th><th>Penjualan</th><th>HPP</th><th>Margin</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${rupiah(x.sales)}</td><td>${rupiah(x.hpp)}</td><td class="money">${rupiah(x.sales-x.hpp)}</td></tr>`).join('')}</tbody></table>`:'<p style="color:var(--muted)">Belum ada penjualan.</p>'}
function renderAll(){renderDashboard();renderPOS();renderProducts();renderTransactions();renderCashflow();renderReports();document.getElementById('apiUrl').value=apiUrl()}

document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.page)));document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.goto)));document.getElementById('productSearch').addEventListener('input',renderPOS);document.getElementById('discount').addEventListener('input',renderPOS);document.getElementById('paidAmount').addEventListener('input',renderPOS);document.getElementById('checkoutBtn').addEventListener('click',checkout);document.getElementById('clearCart').addEventListener('click',()=>{cart=[];renderPOS()});document.getElementById('transactionSearch').addEventListener('input',renderTransactions);document.getElementById('transactionMethod').addEventListener('change',renderTransactions);document.getElementById('addProductBtn').addEventListener('click',()=>openProduct());document.getElementById('closeModal').addEventListener('click',()=>document.getElementById('modal').classList.add('hidden'));
document.getElementById('productForm').addEventListener('submit',async e=>{e.preventDefault();const pid=document.getElementById('productId').value,p={id:pid||uid(),name:document.getElementById('productName').value.trim(),category:document.getElementById('productCategory').value.trim(),price:Number(document.getElementById('productPrice').value),cost:Number(document.getElementById('productCost').value),stock:Number(document.getElementById('productStock').value)};try{if(apiUrl()){db=await apiPost('saveProduct',{product:p});setStatus(true)}else{const idx=db.products.findIndex(x=>x.id===pid);if(idx>=0)db.products[idx]=p;else db.products.push(p);localSave()}document.getElementById('modal').classList.add('hidden');renderAll();toast('Produk berhasil disimpan')}catch(err){toast('Gagal menyimpan: '+err.message)}});
async function saveFlow(type,descId,amountId){const item={id:uid(),date:today(),time:new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),type,category:type==='income'?'Lainnya':'Operasional',description:document.getElementById(descId).value.trim(),amount:Number(document.getElementById(amountId).value)};try{if(apiUrl()){db=await apiPost('saveCashflow',{item});setStatus(true)}else{db.cashflows.push(item);localSave()}renderAll();toast(type==='income'?'Pemasukan disimpan':'Pengeluaran disimpan')}catch(err){toast('Gagal menyimpan: '+err.message)}}
document.getElementById('incomeForm').addEventListener('submit',async e=>{e.preventDefault();await saveFlow('income','incomeDesc','incomeAmount');e.target.reset()});document.getElementById('expenseForm').addEventListener('submit',async e=>{e.preventDefault();await saveFlow('expense','expenseDesc','expenseAmount');e.target.reset()});document.getElementById('saveApiBtn').addEventListener('click',async()=>{const u=document.getElementById('apiUrl').value.trim().replace(/\/$/,'');if(!u)return toast('Masukkan URL Web App');localStorage.setItem(API_KEY,u);document.getElementById('connectionResult').textContent='Menguji koneksi...';try{db=await apiGet('bootstrap');localStorage.setItem(LOCAL_KEY,JSON.stringify(db));setStatus(true);document.getElementById('connectionResult').textContent='✅ Terhubung ke Google Sheets';renderAll();toast('Koneksi berhasil')}catch(e){setStatus(false);document.getElementById('connectionResult').textContent='❌ '+e.message;toast('Koneksi gagal')}});document.getElementById('clearApiBtn').addEventListener('click',()=>{localStorage.removeItem(API_KEY);setStatus(false);document.getElementById('apiUrl').value='';document.getElementById('connectionResult').textContent='Mode lokal aktif';toast('Koneksi dihapus')});document.getElementById('syncBtn').addEventListener('click',syncFromSheets);document.getElementById('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`deanti-bakery-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)});document.getElementById('reportDate').value=today();setStatus(!!apiUrl());renderAll();if(apiUrl())syncFromSheets();